# -*- coding: utf-8 -*-
"""
This script generates the rigid demand for H2 and the flexible PtL H2 demand as
hourly time series and also generates the capacities for PtL production.

@author: Eva Joskin
"""

import pandas as pd
import pickle
import sys,os
sys.path.append(os.path.abspath(r'../..')) 
from dispaset_sidetools.common import make_dir

# %% Adjustable inputs that should be modified
# Scenario definition
WRITE_CSV_FILES = True  # Write csv database
SCENARIO = 'NearZeroCarbon'  # Scenario name, used for naming csv files
CASE = 'ALLFLEX'  # Case name, used for naming csv files
SOURCE = 'JRC_EU_TIMES_'  # Source name, used for naming csv files
EFF_DIESEL = 0.78 # Efficiency of hydrogenation to diesel
EFF_METHANOL = 0.818 # Efficiency of hydrogenation to methanol
PtL = False # if false, demand is summed in rigid demand

# %% Inputs
# Folder destinations
input_folder = '../../Inputs/'  # Standard input folder
source_folder = 'JRC_EU_TIMES/'
output_folder = '../../Outputs/'  # Standard output folder
scenario = SCENARIO + '/'

# %% Load data
h2_normal_demand = pd.read_excel(
    input_folder + source_folder + scenario + 'TIMES_H2_Demand_2050.xlsx', 
    header=0, index_col = 0, skiprows = 2)
h2_demand_PtL = pd.read_excel(
    input_folder + source_folder + scenario + 'TIMES_H2_Demand_PtL_2050.xlsx', 
    index_col = 0, skiprows = 1)
PtL_capacity = pd.read_excel(
    input_folder + source_folder + scenario + 'TIMES_PtL_Capacities_2050.xlsx', 
    index_col = 0, skiprows = 1, header=0)

# %% Correct H2 demand for PtL (what we have is demand for diesel and methanol, not for H2)
for h in h2_demand_PtL.columns:
    if "Diesel" in h:
        h2_demand_PtL.loc[:,h] = h2_demand_PtL.loc[:,h]/EFF_DIESEL
    elif "Methanol" in h:
        h2_demand_PtL.loc[:,h] = h2_demand_PtL.loc[:,h]/EFF_METHANOL

h2_demand_PtL_final=pd.DataFrame(columns=['2050'], index=h2_normal_demand.index).fillna(0)
for c in h2_demand_PtL.index:
    h2_demand_PtL_final.loc[c]=h2_demand_PtL.loc[c,:].sum()        
    

# %% Flat demand over the year for rigid and PtL demands
dates = pd.date_range(start='1/1/2050', end='31/12/2050 23:00:00', freq='H')

h2_rigid_demand_time_series = pd.DataFrame(0,index=dates, columns = h2_normal_demand.index)
h2_PtL_demand_time_series = pd.DataFrame(0,index=dates, columns = h2_demand_PtL_final.index)

comparison = h2_rigid_demand_time_series.index == h2_PtL_demand_time_series.index
if not comparison.all():
    print('Error: Not the same number of countries in PtL demand and normal demand!')
    sys.exit()
    
for c in h2_normal_demand.index:
    h2_rigid_demand_time_series.loc[:,c] = h2_normal_demand.loc[c].item()/(len(dates)*3.6e-6) # flat demand [MWh]
    h2_PtL_demand_time_series.loc[:,c] = h2_demand_PtL_final.loc[c].item()/(len(dates)*3.6e-6) # flat demand [MWh]
    if PtL is not True:
        h2_rigid_demand_time_series.loc[:,c] += h2_PtL_demand_time_series.loc[:,c]
        h2_PtL_demand_time_series.loc[:,c] = 0
    
# %% Create csv file format
# Load pickle data for power plants generated by get_Capacities script
pickle_off = open(input_folder + source_folder+ scenario + SOURCE + SCENARIO + '_' + str(2050) + '_' + CASE + '.p', 'rb')
allunits = pickle.load(pickle_off)  
h2_rigid_demand_final=pd.DataFrame(index=h2_rigid_demand_time_series.index)
h2_PtL_demand_final=pd.DataFrame(index=h2_PtL_demand_time_series.index)
a=1

for c in allunits.keys():
    a=0
    for u in allunits[c].index:
        if 'P2GS' in u:
            h2_rigid_demand_final[u] = h2_rigid_demand_time_series.loc[:,c].copy()
            h2_PtL_demand_final[u] = h2_PtL_demand_time_series.loc[:,c].copy()
            a=1
    if a==0:
        print('[CRITICAL  ]:' + c + '  has a demand for H2 but no electrolyzers to produce it')

#%% Sum capacities PtL
PtL_capacity_tot = pd.DataFrame(columns = ['Capacity'], index = h2_rigid_demand_final.columns)
    
for c in PtL_capacity.index:
    for country in PtL_capacity_tot.index:
        if c in country:
            PtL_capacity_tot.loc[country] = PtL_capacity.loc[c,:].sum()
PtL_capacity_tot = PtL_capacity_tot.fillna(0)*1000 # GW-> MW 
    
# %% Write csv file:
def write_csv_files(h2_rigid, h2_PtL, PtL_cap, write_csv=None):
    """
    Function that generates .csv files in the Output/Database/h2_demand/ folder
    """
    if write_csv is True:
        make_dir((output_folder))
        make_dir(output_folder + source_folder + 'Database')
        folder = output_folder + source_folder + 'Database/' + scenario + 'H2_demand/'
        make_dir(folder)
        h2_rigid.to_csv(folder +  '/' + 'H2_rigid_Demand_2050_' + CASE + '.csv')
        h2_PtL.to_csv(folder+ '/' + 'H2_PtL_Demand_2050_' + CASE +'.csv')
        PtL_cap.to_csv(folder + '/' + 'PtL_capacities_2050_' + CASE + '.csv')
    else:
        print('[WARNING ]: ' + 'WRITE_CSV_FILES = False, unable to write .csv files')


write_csv_files(h2_rigid_demand_final,h2_PtL_demand_final,PtL_capacity_tot , WRITE_CSV_FILES) 
